apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: hello
data:
  default.conf: |
    server {
        listen 80;

        # 기본 페이지
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # FastAPI 리버스 프록시
        location /api {
            proxy_pass http://fastapi-service.hello.svc.cluster.local;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
